kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-zookeeper.yml
kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-kafka.yml
kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-schema-registry.yml
kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-kowl.yml
kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-redis.yml
kubectl delete -f Pipeline/Kubernetes/Infrastructure/deploy-mongodb.yml
kubectl delete -f Pipeline/Kubernetes/Services/deploy-input-service.yml
kubectl delete -f Pipeline/Kubernetes/Services/deploy-collision-service.yml
kubectl delete -f Pipeline/Kubernetes/Services/deploy-world-service.yml
kubectl delete -f Pipeline/Kubernetes/Services/deploy-projectile-service.yml
kubectl delete -f Pipeline/Kubernetes/Services/deploy-ai-service.yml
