// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Collision_M.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClassLibrary.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from Collision_M.proto</summary>
  public static partial class CollisionMReflection {

    #region Descriptor
    /// <summary>File descriptor for Collision_M.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollisionMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb2xsaXNpb25fTS5wcm90bxIeQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlBy",
            "b3RvYnVmGg1DbGFzc2VzLnByb3RvItsCCgtDb2xsaXNpb25fTRIQCghFbnRp",
            "dHlJZBgBIAEoCRI+CgpFbnRpdHlUeXBlGAIgASgOMiouQ2xhc3NMaWJyYXJ5",
            "Lk1lc3NhZ2VzLlByb3RvYnVmLkVudGl0eVR5cGUSQwoMRnJvbUxvY2F0aW9u",
            "GAMgASgLMi0uQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlByb3RvYnVmLkNvb3Jk",
            "aW5hdGVzX00SQQoKVG9Mb2NhdGlvbhgEIAEoCzItLkNsYXNzTGlicmFyeS5N",
            "ZXNzYWdlcy5Qcm90b2J1Zi5Db29yZGluYXRlc19NEkAKCURpcmVjdGlvbhgF",
            "IAEoCzItLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1Zi5Db29yZGlu",
            "YXRlc19NEhIKCkxhc3RVcGRhdGUYBiABKAESDwoHRXZlbnRJZBgHIAEoCRIL",
            "CgNUVEwYCCABKAEqLAoKRW50aXR5VHlwZRIKCgZQbGF5ZXIQABIKCgZCdWxs",
            "ZXQQARIGCgJBaRACQiGqAh5DbGFzc0xpYnJhcnkuTWVzc2FnZXMuUHJvdG9i",
            "dWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClassLibrary.Messages.Protobuf.ClassesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClassLibrary.Messages.Protobuf.EntityType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClassLibrary.Messages.Protobuf.Collision_M), global::ClassLibrary.Messages.Protobuf.Collision_M.Parser, new[]{ "EntityId", "EntityType", "FromLocation", "ToLocation", "Direction", "LastUpdate", "EventId", "TTL" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EntityType {
    [pbr::OriginalName("Player")] Player = 0,
    [pbr::OriginalName("Bullet")] Bullet = 1,
    [pbr::OriginalName("Ai")] Ai = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Collision_M : pb::IMessage<Collision_M>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Collision_M> _parser = new pb::MessageParser<Collision_M>(() => new Collision_M());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Collision_M> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClassLibrary.Messages.Protobuf.CollisionMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Collision_M() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Collision_M(Collision_M other) : this() {
      entityId_ = other.entityId_;
      entityType_ = other.entityType_;
      fromLocation_ = other.fromLocation_ != null ? other.fromLocation_.Clone() : null;
      toLocation_ = other.toLocation_ != null ? other.toLocation_.Clone() : null;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      lastUpdate_ = other.lastUpdate_;
      eventId_ = other.eventId_;
      tTL_ = other.tTL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Collision_M Clone() {
      return new Collision_M(this);
    }

    /// <summary>Field number for the "EntityId" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private string entityId_ = "";
    /// <summary>
    /// UUIDs are represented as strings in Protobuf
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityId {
      get { return entityId_; }
      set {
        entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EntityType" field.</summary>
    public const int EntityTypeFieldNumber = 2;
    private global::ClassLibrary.Messages.Protobuf.EntityType entityType_ = global::ClassLibrary.Messages.Protobuf.EntityType.Player;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.EntityType EntityType {
      get { return entityType_; }
      set {
        entityType_ = value;
      }
    }

    /// <summary>Field number for the "FromLocation" field.</summary>
    public const int FromLocationFieldNumber = 3;
    private global::ClassLibrary.Messages.Protobuf.Coordinates_M fromLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates_M FromLocation {
      get { return fromLocation_; }
      set {
        fromLocation_ = value;
      }
    }

    /// <summary>Field number for the "ToLocation" field.</summary>
    public const int ToLocationFieldNumber = 4;
    private global::ClassLibrary.Messages.Protobuf.Coordinates_M toLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates_M ToLocation {
      get { return toLocation_; }
      set {
        toLocation_ = value;
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 5;
    private global::ClassLibrary.Messages.Protobuf.Coordinates_M direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates_M Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "LastUpdate" field.</summary>
    public const int LastUpdateFieldNumber = 6;
    private double lastUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LastUpdate {
      get { return lastUpdate_; }
      set {
        lastUpdate_ = value;
      }
    }

    /// <summary>Field number for the "EventId" field.</summary>
    public const int EventIdFieldNumber = 7;
    private string eventId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TTL" field.</summary>
    public const int TTLFieldNumber = 8;
    private double tTL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TTL {
      get { return tTL_; }
      set {
        tTL_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Collision_M);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Collision_M other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (EntityType != other.EntityType) return false;
      if (!object.Equals(FromLocation, other.FromLocation)) return false;
      if (!object.Equals(ToLocation, other.ToLocation)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastUpdate, other.LastUpdate)) return false;
      if (EventId != other.EventId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TTL, other.TTL)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
      if (EntityType != global::ClassLibrary.Messages.Protobuf.EntityType.Player) hash ^= EntityType.GetHashCode();
      if (fromLocation_ != null) hash ^= FromLocation.GetHashCode();
      if (toLocation_ != null) hash ^= ToLocation.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (LastUpdate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastUpdate);
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (TTL != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TTL);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (EntityType != global::ClassLibrary.Messages.Protobuf.EntityType.Player) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EntityType);
      }
      if (fromLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FromLocation);
      }
      if (toLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToLocation);
      }
      if (direction_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Direction);
      }
      if (LastUpdate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(LastUpdate);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(EventId);
      }
      if (TTL != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(TTL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (EntityType != global::ClassLibrary.Messages.Protobuf.EntityType.Player) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EntityType);
      }
      if (fromLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FromLocation);
      }
      if (toLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToLocation);
      }
      if (direction_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Direction);
      }
      if (LastUpdate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(LastUpdate);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(EventId);
      }
      if (TTL != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(TTL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
      }
      if (EntityType != global::ClassLibrary.Messages.Protobuf.EntityType.Player) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EntityType);
      }
      if (fromLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FromLocation);
      }
      if (toLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToLocation);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (LastUpdate != 0D) {
        size += 1 + 8;
      }
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (TTL != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Collision_M other) {
      if (other == null) {
        return;
      }
      if (other.EntityId.Length != 0) {
        EntityId = other.EntityId;
      }
      if (other.EntityType != global::ClassLibrary.Messages.Protobuf.EntityType.Player) {
        EntityType = other.EntityType;
      }
      if (other.fromLocation_ != null) {
        if (fromLocation_ == null) {
          FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
        }
        FromLocation.MergeFrom(other.FromLocation);
      }
      if (other.toLocation_ != null) {
        if (toLocation_ == null) {
          ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
        }
        ToLocation.MergeFrom(other.ToLocation);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.LastUpdate != 0D) {
        LastUpdate = other.LastUpdate;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.TTL != 0D) {
        TTL = other.TTL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            EntityType = (global::ClassLibrary.Messages.Protobuf.EntityType) input.ReadEnum();
            break;
          }
          case 26: {
            if (fromLocation_ == null) {
              FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(FromLocation);
            break;
          }
          case 34: {
            if (toLocation_ == null) {
              ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(ToLocation);
            break;
          }
          case 42: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 49: {
            LastUpdate = input.ReadDouble();
            break;
          }
          case 58: {
            EventId = input.ReadString();
            break;
          }
          case 65: {
            TTL = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            EntityType = (global::ClassLibrary.Messages.Protobuf.EntityType) input.ReadEnum();
            break;
          }
          case 26: {
            if (fromLocation_ == null) {
              FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(FromLocation);
            break;
          }
          case 34: {
            if (toLocation_ == null) {
              ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(ToLocation);
            break;
          }
          case 42: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 49: {
            LastUpdate = input.ReadDouble();
            break;
          }
          case 58: {
            EventId = input.ReadString();
            break;
          }
          case 65: {
            TTL = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
