// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CollisionCheck.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClassLibrary.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from CollisionCheck.proto</summary>
  public static partial class CollisionCheckReflection {

    #region Descriptor
    /// <summary>File descriptor for CollisionCheck.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollisionCheckReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb2xsaXNpb25DaGVjay5wcm90bxIeQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2Vz",
            "LlByb3RvYnVmGgxDb21tb24ucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8i8AIKDkNvbGxpc2lvbkNoZWNrEhAKCEVudGl0eUlkGAEg",
            "ASgJEjoKBkVudGl0eRgCIAEoDjIqLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Q",
            "cm90b2J1Zi5FbnRpdHlUeXBlEkEKDEZyb21Mb2NhdGlvbhgDIAEoCzIrLkNs",
            "YXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1Zi5Db29yZGluYXRlcxI/CgpU",
            "b0xvY2F0aW9uGAQgASgLMisuQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlByb3Rv",
            "YnVmLkNvb3JkaW5hdGVzEg0KBVRpbWVyGAUgASgBEg8KB0V2ZW50SWQYBiAB",
            "KAkSPgoJRGlyZWN0aW9uGAcgASgLMisuQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2Vz",
            "LlByb3RvYnVmLkNvb3JkaW5hdGVzEiwKCEdhbWVUaW1lGAggASgLMhouZ29v",
            "Z2xlLnByb3RvYnVmLlRpbWVzdGFtcCooCgpFbnRpdHlUeXBlEgoKBkF2YXRh",
            "chAAEg4KClByb2plY3RpbGUQAUIhqgIeQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2Vz",
            "LlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClassLibrary.Messages.Protobuf.CommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClassLibrary.Messages.Protobuf.EntityType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClassLibrary.Messages.Protobuf.CollisionCheck), global::ClassLibrary.Messages.Protobuf.CollisionCheck.Parser, new[]{ "EntityId", "Entity", "FromLocation", "ToLocation", "Timer", "EventId", "Direction", "GameTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EntityType {
    [pbr::OriginalName("Avatar")] Avatar = 0,
    [pbr::OriginalName("Projectile")] Projectile = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CollisionCheck : pb::IMessage<CollisionCheck>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollisionCheck> _parser = new pb::MessageParser<CollisionCheck>(() => new CollisionCheck());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CollisionCheck> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClassLibrary.Messages.Protobuf.CollisionCheckReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionCheck() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionCheck(CollisionCheck other) : this() {
      entityId_ = other.entityId_;
      entity_ = other.entity_;
      fromLocation_ = other.fromLocation_ != null ? other.fromLocation_.Clone() : null;
      toLocation_ = other.toLocation_ != null ? other.toLocation_.Clone() : null;
      timer_ = other.timer_;
      eventId_ = other.eventId_;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      gameTime_ = other.gameTime_ != null ? other.gameTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionCheck Clone() {
      return new CollisionCheck(this);
    }

    /// <summary>Field number for the "EntityId" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private string entityId_ = "";
    /// <summary>
    /// UUIDs are represented as strings in Protobuf
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityId {
      get { return entityId_; }
      set {
        entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Entity" field.</summary>
    public const int EntityFieldNumber = 2;
    private global::ClassLibrary.Messages.Protobuf.EntityType entity_ = global::ClassLibrary.Messages.Protobuf.EntityType.Avatar;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.EntityType Entity {
      get { return entity_; }
      set {
        entity_ = value;
      }
    }

    /// <summary>Field number for the "FromLocation" field.</summary>
    public const int FromLocationFieldNumber = 3;
    private global::ClassLibrary.Messages.Protobuf.Coordinates fromLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates FromLocation {
      get { return fromLocation_; }
      set {
        fromLocation_ = value;
      }
    }

    /// <summary>Field number for the "ToLocation" field.</summary>
    public const int ToLocationFieldNumber = 4;
    private global::ClassLibrary.Messages.Protobuf.Coordinates toLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates ToLocation {
      get { return toLocation_; }
      set {
        toLocation_ = value;
      }
    }

    /// <summary>Field number for the "Timer" field.</summary>
    public const int TimerFieldNumber = 5;
    private double timer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Timer {
      get { return timer_; }
      set {
        timer_ = value;
      }
    }

    /// <summary>Field number for the "EventId" field.</summary>
    public const int EventIdFieldNumber = 6;
    private string eventId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 7;
    private global::ClassLibrary.Messages.Protobuf.Coordinates direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "GameTime" field.</summary>
    public const int GameTimeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp gameTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp GameTime {
      get { return gameTime_; }
      set {
        gameTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CollisionCheck);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CollisionCheck other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (Entity != other.Entity) return false;
      if (!object.Equals(FromLocation, other.FromLocation)) return false;
      if (!object.Equals(ToLocation, other.ToLocation)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timer, other.Timer)) return false;
      if (EventId != other.EventId) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (!object.Equals(GameTime, other.GameTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
      if (Entity != global::ClassLibrary.Messages.Protobuf.EntityType.Avatar) hash ^= Entity.GetHashCode();
      if (fromLocation_ != null) hash ^= FromLocation.GetHashCode();
      if (toLocation_ != null) hash ^= ToLocation.GetHashCode();
      if (Timer != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timer);
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (gameTime_ != null) hash ^= GameTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Entity != global::ClassLibrary.Messages.Protobuf.EntityType.Avatar) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Entity);
      }
      if (fromLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FromLocation);
      }
      if (toLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToLocation);
      }
      if (Timer != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Timer);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (direction_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Direction);
      }
      if (gameTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(GameTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Entity != global::ClassLibrary.Messages.Protobuf.EntityType.Avatar) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Entity);
      }
      if (fromLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FromLocation);
      }
      if (toLocation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToLocation);
      }
      if (Timer != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Timer);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (direction_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Direction);
      }
      if (gameTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(GameTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
      }
      if (Entity != global::ClassLibrary.Messages.Protobuf.EntityType.Avatar) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Entity);
      }
      if (fromLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FromLocation);
      }
      if (toLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToLocation);
      }
      if (Timer != 0D) {
        size += 1 + 8;
      }
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (gameTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CollisionCheck other) {
      if (other == null) {
        return;
      }
      if (other.EntityId.Length != 0) {
        EntityId = other.EntityId;
      }
      if (other.Entity != global::ClassLibrary.Messages.Protobuf.EntityType.Avatar) {
        Entity = other.Entity;
      }
      if (other.fromLocation_ != null) {
        if (fromLocation_ == null) {
          FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        FromLocation.MergeFrom(other.FromLocation);
      }
      if (other.toLocation_ != null) {
        if (toLocation_ == null) {
          ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        ToLocation.MergeFrom(other.ToLocation);
      }
      if (other.Timer != 0D) {
        Timer = other.Timer;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.gameTime_ != null) {
        if (gameTime_ == null) {
          GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        GameTime.MergeFrom(other.GameTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Entity = (global::ClassLibrary.Messages.Protobuf.EntityType) input.ReadEnum();
            break;
          }
          case 26: {
            if (fromLocation_ == null) {
              FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(FromLocation);
            break;
          }
          case 34: {
            if (toLocation_ == null) {
              ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(ToLocation);
            break;
          }
          case 41: {
            Timer = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 58: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 66: {
            if (gameTime_ == null) {
              GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GameTime);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Entity = (global::ClassLibrary.Messages.Protobuf.EntityType) input.ReadEnum();
            break;
          }
          case 26: {
            if (fromLocation_ == null) {
              FromLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(FromLocation);
            break;
          }
          case 34: {
            if (toLocation_ == null) {
              ToLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(ToLocation);
            break;
          }
          case 41: {
            Timer = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 58: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 66: {
            if (gameTime_ == null) {
              GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GameTime);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
