// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Input.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClassLibrary.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from Input.proto</summary>
  public static partial class InputReflection {

    #region Descriptor
    /// <summary>File descriptor for Input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtJbnB1dC5wcm90bxIeQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlByb3RvYnVm",
            "GgxDb21tb24ucHJvdG8iuAIKBUlucHV0EhAKCFBsYXllcklkGAEgASgJEkMK",
            "DlBsYXllckxvY2F0aW9uGAIgASgLMisuQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2Vz",
            "LlByb3RvYnVmLkNvb3JkaW5hdGVzEkIKDU1vdXNlTG9jYXRpb24YAyABKAsy",
            "Ky5DbGFzc0xpYnJhcnkuTWVzc2FnZXMuUHJvdG9idWYuQ29vcmRpbmF0ZXMS",
            "OQoIS2V5SW5wdXQYBCADKA4yJy5DbGFzc0xpYnJhcnkuTWVzc2FnZXMuUHJv",
            "dG9idWYuR2FtZUtleRIQCghHYW1lVGltZRgFIAEoARIPCgdFdmVudElkGAYg",
            "ASgJEjYKBlNvdXJjZRgHIAEoDjImLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Q",
            "cm90b2J1Zi5Tb3VyY2UqSgoHR2FtZUtleRIGCgJVcBAAEggKBERvd24QARII",
            "CgRMZWZ0EAISCQoFUmlnaHQQAxIKCgZBdHRhY2sQBBIMCghJbnRlcmFjdBAF",
            "KhwKBlNvdXJjZRIKCgZQbGF5ZXIQABIGCgJBaRABQiGqAh5DbGFzc0xpYnJh",
            "cnkuTWVzc2FnZXMuUHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClassLibrary.Messages.Protobuf.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClassLibrary.Messages.Protobuf.GameKey), typeof(global::ClassLibrary.Messages.Protobuf.Source), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClassLibrary.Messages.Protobuf.Input), global::ClassLibrary.Messages.Protobuf.Input.Parser, new[]{ "PlayerId", "PlayerLocation", "MouseLocation", "KeyInput", "GameTime", "EventId", "Source" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameKey {
    [pbr::OriginalName("Up")] Up = 0,
    [pbr::OriginalName("Down")] Down = 1,
    [pbr::OriginalName("Left")] Left = 2,
    [pbr::OriginalName("Right")] Right = 3,
    [pbr::OriginalName("Attack")] Attack = 4,
    [pbr::OriginalName("Interact")] Interact = 5,
  }

  public enum Source {
    [pbr::OriginalName("Player")] Player = 0,
    [pbr::OriginalName("Ai")] Ai = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Input : pb::IMessage<Input>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Input> _parser = new pb::MessageParser<Input>(() => new Input());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Input> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClassLibrary.Messages.Protobuf.InputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input(Input other) : this() {
      playerId_ = other.playerId_;
      playerLocation_ = other.playerLocation_ != null ? other.playerLocation_.Clone() : null;
      mouseLocation_ = other.mouseLocation_ != null ? other.mouseLocation_.Clone() : null;
      keyInput_ = other.keyInput_.Clone();
      gameTime_ = other.gameTime_;
      eventId_ = other.eventId_;
      source_ = other.source_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input Clone() {
      return new Input(this);
    }

    /// <summary>Field number for the "PlayerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private string playerId_ = "";
    /// <summary>
    /// UUIDs are represented as strings in proto
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlayerId {
      get { return playerId_; }
      set {
        playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PlayerLocation" field.</summary>
    public const int PlayerLocationFieldNumber = 2;
    private global::ClassLibrary.Messages.Protobuf.Coordinates playerLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates PlayerLocation {
      get { return playerLocation_; }
      set {
        playerLocation_ = value;
      }
    }

    /// <summary>Field number for the "MouseLocation" field.</summary>
    public const int MouseLocationFieldNumber = 3;
    private global::ClassLibrary.Messages.Protobuf.Coordinates mouseLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates MouseLocation {
      get { return mouseLocation_; }
      set {
        mouseLocation_ = value;
      }
    }

    /// <summary>Field number for the "KeyInput" field.</summary>
    public const int KeyInputFieldNumber = 4;
    private static readonly pb::FieldCodec<global::ClassLibrary.Messages.Protobuf.GameKey> _repeated_keyInput_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::ClassLibrary.Messages.Protobuf.GameKey) x);
    private readonly pbc::RepeatedField<global::ClassLibrary.Messages.Protobuf.GameKey> keyInput_ = new pbc::RepeatedField<global::ClassLibrary.Messages.Protobuf.GameKey>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClassLibrary.Messages.Protobuf.GameKey> KeyInput {
      get { return keyInput_; }
    }

    /// <summary>Field number for the "GameTime" field.</summary>
    public const int GameTimeFieldNumber = 5;
    private double gameTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double GameTime {
      get { return gameTime_; }
      set {
        gameTime_ = value;
      }
    }

    /// <summary>Field number for the "EventId" field.</summary>
    public const int EventIdFieldNumber = 6;
    private string eventId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Source" field.</summary>
    public const int SourceFieldNumber = 7;
    private global::ClassLibrary.Messages.Protobuf.Source source_ = global::ClassLibrary.Messages.Protobuf.Source.Player;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Source Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Input);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Input other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(PlayerLocation, other.PlayerLocation)) return false;
      if (!object.Equals(MouseLocation, other.MouseLocation)) return false;
      if(!keyInput_.Equals(other.keyInput_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(GameTime, other.GameTime)) return false;
      if (EventId != other.EventId) return false;
      if (Source != other.Source) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
      if (playerLocation_ != null) hash ^= PlayerLocation.GetHashCode();
      if (mouseLocation_ != null) hash ^= MouseLocation.GetHashCode();
      hash ^= keyInput_.GetHashCode();
      if (GameTime != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(GameTime);
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (Source != global::ClassLibrary.Messages.Protobuf.Source.Player) hash ^= Source.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerId);
      }
      if (playerLocation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerLocation);
      }
      if (mouseLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseLocation);
      }
      keyInput_.WriteTo(output, _repeated_keyInput_codec);
      if (GameTime != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(GameTime);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (Source != global::ClassLibrary.Messages.Protobuf.Source.Player) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Source);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerId);
      }
      if (playerLocation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerLocation);
      }
      if (mouseLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseLocation);
      }
      keyInput_.WriteTo(ref output, _repeated_keyInput_codec);
      if (GameTime != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(GameTime);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (Source != global::ClassLibrary.Messages.Protobuf.Source.Player) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Source);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
      }
      if (playerLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerLocation);
      }
      if (mouseLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MouseLocation);
      }
      size += keyInput_.CalculateSize(_repeated_keyInput_codec);
      if (GameTime != 0D) {
        size += 1 + 8;
      }
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (Source != global::ClassLibrary.Messages.Protobuf.Source.Player) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Source);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Input other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId.Length != 0) {
        PlayerId = other.PlayerId;
      }
      if (other.playerLocation_ != null) {
        if (playerLocation_ == null) {
          PlayerLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        PlayerLocation.MergeFrom(other.PlayerLocation);
      }
      if (other.mouseLocation_ != null) {
        if (mouseLocation_ == null) {
          MouseLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        MouseLocation.MergeFrom(other.MouseLocation);
      }
      keyInput_.Add(other.keyInput_);
      if (other.GameTime != 0D) {
        GameTime = other.GameTime;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.Source != global::ClassLibrary.Messages.Protobuf.Source.Player) {
        Source = other.Source;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PlayerId = input.ReadString();
            break;
          }
          case 18: {
            if (playerLocation_ == null) {
              PlayerLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(PlayerLocation);
            break;
          }
          case 26: {
            if (mouseLocation_ == null) {
              MouseLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(MouseLocation);
            break;
          }
          case 34:
          case 32: {
            keyInput_.AddEntriesFrom(input, _repeated_keyInput_codec);
            break;
          }
          case 41: {
            GameTime = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 56: {
            Source = (global::ClassLibrary.Messages.Protobuf.Source) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PlayerId = input.ReadString();
            break;
          }
          case 18: {
            if (playerLocation_ == null) {
              PlayerLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(PlayerLocation);
            break;
          }
          case 26: {
            if (mouseLocation_ == null) {
              MouseLocation = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(MouseLocation);
            break;
          }
          case 34:
          case 32: {
            keyInput_.AddEntriesFrom(ref input, _repeated_keyInput_codec);
            break;
          }
          case 41: {
            GameTime = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 56: {
            Source = (global::ClassLibrary.Messages.Protobuf.Source) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
