// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldChange.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClassLibrary.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from WorldChange.proto</summary>
  public static partial class WorldChangeReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldChange.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldChangeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFXb3JsZENoYW5nZS5wcm90bxIeQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlBy",
            "b3RvYnVmGgxDb21tb24ucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3Rh",
            "bXAucHJvdG8iqAIKC1dvcmxkQ2hhbmdlEhAKCEVudGl0eUlkGAEgASgJEjoK",
            "BkNoYW5nZRgCIAEoDjIqLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1",
            "Zi5DaGFuZ2VUeXBlEj0KCExvY2F0aW9uGAMgASgLMisuQ2xhc3NMaWJyYXJ5",
            "Lk1lc3NhZ2VzLlByb3RvYnVmLkNvb3JkaW5hdGVzEj4KCURpcmVjdGlvbhgE",
            "IAEoCzIrLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1Zi5Db29yZGlu",
            "YXRlcxINCgVUaW1lchgFIAEoARIPCgdFdmVudElkGAYgASgJEiwKCEdhbWVU",
            "aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpoCgpDaGFu",
            "Z2VUeXBlEg4KCk1vdmVQbGF5ZXIQABIPCgtTcGF3bkJ1bGxldBABEg4KCk1v",
            "dmVCdWxsZXQQAhIQCgxEYW1hZ2VQbGF5ZXIQAxILCgdTcGF3bkFpEAQSCgoG",
            "TW92ZUFpEAVCIaoCHkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1ZmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClassLibrary.Messages.Protobuf.CommonReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClassLibrary.Messages.Protobuf.ChangeType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClassLibrary.Messages.Protobuf.WorldChange), global::ClassLibrary.Messages.Protobuf.WorldChange.Parser, new[]{ "EntityId", "Change", "Location", "Direction", "Timer", "EventId", "GameTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChangeType {
    [pbr::OriginalName("MovePlayer")] MovePlayer = 0,
    [pbr::OriginalName("SpawnBullet")] SpawnBullet = 1,
    [pbr::OriginalName("MoveBullet")] MoveBullet = 2,
    [pbr::OriginalName("DamagePlayer")] DamagePlayer = 3,
    [pbr::OriginalName("SpawnAi")] SpawnAi = 4,
    [pbr::OriginalName("MoveAi")] MoveAi = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldChange : pb::IMessage<WorldChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldChange> _parser = new pb::MessageParser<WorldChange>(() => new WorldChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClassLibrary.Messages.Protobuf.WorldChangeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldChange(WorldChange other) : this() {
      entityId_ = other.entityId_;
      change_ = other.change_;
      location_ = other.location_ != null ? other.location_.Clone() : null;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      timer_ = other.timer_;
      eventId_ = other.eventId_;
      gameTime_ = other.gameTime_ != null ? other.gameTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldChange Clone() {
      return new WorldChange(this);
    }

    /// <summary>Field number for the "EntityId" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private string entityId_ = "";
    /// <summary>
    /// UUIDs are represented as strings in Protobuf
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityId {
      get { return entityId_; }
      set {
        entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Change" field.</summary>
    public const int ChangeFieldNumber = 2;
    private global::ClassLibrary.Messages.Protobuf.ChangeType change_ = global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.ChangeType Change {
      get { return change_; }
      set {
        change_ = value;
      }
    }

    /// <summary>Field number for the "Location" field.</summary>
    public const int LocationFieldNumber = 3;
    private global::ClassLibrary.Messages.Protobuf.Coordinates location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 4;
    private global::ClassLibrary.Messages.Protobuf.Coordinates direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "Timer" field.</summary>
    public const int TimerFieldNumber = 5;
    private double timer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Timer {
      get { return timer_; }
      set {
        timer_ = value;
      }
    }

    /// <summary>Field number for the "EventId" field.</summary>
    public const int EventIdFieldNumber = 6;
    private string eventId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GameTime" field.</summary>
    public const int GameTimeFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp gameTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp GameTime {
      get { return gameTime_; }
      set {
        gameTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (Change != other.Change) return false;
      if (!object.Equals(Location, other.Location)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timer, other.Timer)) return false;
      if (EventId != other.EventId) return false;
      if (!object.Equals(GameTime, other.GameTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
      if (Change != global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer) hash ^= Change.GetHashCode();
      if (location_ != null) hash ^= Location.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (Timer != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timer);
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (gameTime_ != null) hash ^= GameTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Change);
      }
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (direction_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Direction);
      }
      if (Timer != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Timer);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (gameTime_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GameTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Change);
      }
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (direction_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Direction);
      }
      if (Timer != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Timer);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (gameTime_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GameTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Change);
      }
      if (location_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (Timer != 0D) {
        size += 1 + 8;
      }
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (gameTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldChange other) {
      if (other == null) {
        return;
      }
      if (other.EntityId.Length != 0) {
        EntityId = other.EntityId;
      }
      if (other.Change != global::ClassLibrary.Messages.Protobuf.ChangeType.MovePlayer) {
        Change = other.Change;
      }
      if (other.location_ != null) {
        if (location_ == null) {
          Location = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        Location.MergeFrom(other.Location);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.Timer != 0D) {
        Timer = other.Timer;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.gameTime_ != null) {
        if (gameTime_ == null) {
          GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        GameTime.MergeFrom(other.GameTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Change = (global::ClassLibrary.Messages.Protobuf.ChangeType) input.ReadEnum();
            break;
          }
          case 26: {
            if (location_ == null) {
              Location = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Location);
            break;
          }
          case 34: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 41: {
            Timer = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 58: {
            if (gameTime_ == null) {
              GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GameTime);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Change = (global::ClassLibrary.Messages.Protobuf.ChangeType) input.ReadEnum();
            break;
          }
          case 26: {
            if (location_ == null) {
              Location = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Location);
            break;
          }
          case 34: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 41: {
            Timer = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 58: {
            if (gameTime_ == null) {
              GameTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GameTime);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
