// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: World_M.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClassLibrary.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from World_M.proto</summary>
  public static partial class WorldMReflection {

    #region Descriptor
    /// <summary>File descriptor for World_M.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Xb3JsZF9NLnByb3RvEh5DbGFzc0xpYnJhcnkuTWVzc2FnZXMuUHJvdG9i",
            "dWYaDUNsYXNzZXMucHJvdG8iiAIKB1dvcmxkX00SEAoIRW50aXR5SWQYASAB",
            "KAkSNgoGQ2hhbmdlGAIgASgOMiYuQ2xhc3NMaWJyYXJ5Lk1lc3NhZ2VzLlBy",
            "b3RvYnVmLkNoYW5nZRI/CghMb2NhdGlvbhgDIAEoCzItLkNsYXNzTGlicmFy",
            "eS5NZXNzYWdlcy5Qcm90b2J1Zi5Db29yZGluYXRlc19NEkAKCURpcmVjdGlv",
            "bhgEIAEoCzItLkNsYXNzTGlicmFyeS5NZXNzYWdlcy5Qcm90b2J1Zi5Db29y",
            "ZGluYXRlc19NEhIKCkxhc3RVcGRhdGUYBSABKAESDwoHRXZlbnRJZBgGIAEo",
            "CRILCgNUVEwYByABKAEqYwoGQ2hhbmdlEg8KC0RhbWFnZUFnZW50EAASDwoL",
            "U3Bhd25CdWxsZXQQARIOCgpNb3ZlQnVsbGV0EAISDgoKTW92ZVBsYXllchAD",
            "EgsKB1NwYXduQWkQBBIKCgZNb3ZlQWkQBUIhqgIeQ2xhc3NMaWJyYXJ5Lk1l",
            "c3NhZ2VzLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClassLibrary.Messages.Protobuf.ClassesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClassLibrary.Messages.Protobuf.Change), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClassLibrary.Messages.Protobuf.World_M), global::ClassLibrary.Messages.Protobuf.World_M.Parser, new[]{ "EntityId", "Change", "Location", "Direction", "LastUpdate", "EventId", "TTL" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Change {
    [pbr::OriginalName("DamageAgent")] DamageAgent = 0,
    [pbr::OriginalName("SpawnBullet")] SpawnBullet = 1,
    [pbr::OriginalName("MoveBullet")] MoveBullet = 2,
    [pbr::OriginalName("MovePlayer")] MovePlayer = 3,
    [pbr::OriginalName("SpawnAi")] SpawnAi = 4,
    [pbr::OriginalName("MoveAi")] MoveAi = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class World_M : pb::IMessage<World_M>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<World_M> _parser = new pb::MessageParser<World_M>(() => new World_M());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<World_M> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClassLibrary.Messages.Protobuf.WorldMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World_M() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World_M(World_M other) : this() {
      entityId_ = other.entityId_;
      change_ = other.change_;
      location_ = other.location_ != null ? other.location_.Clone() : null;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      lastUpdate_ = other.lastUpdate_;
      eventId_ = other.eventId_;
      tTL_ = other.tTL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public World_M Clone() {
      return new World_M(this);
    }

    /// <summary>Field number for the "EntityId" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private string entityId_ = "";
    /// <summary>
    /// UUIDs are represented as strings in Protobuf
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityId {
      get { return entityId_; }
      set {
        entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Change" field.</summary>
    public const int ChangeFieldNumber = 2;
    private global::ClassLibrary.Messages.Protobuf.Change change_ = global::ClassLibrary.Messages.Protobuf.Change.DamageAgent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Change Change {
      get { return change_; }
      set {
        change_ = value;
      }
    }

    /// <summary>Field number for the "Location" field.</summary>
    public const int LocationFieldNumber = 3;
    private global::ClassLibrary.Messages.Protobuf.Coordinates_M location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates_M Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 4;
    private global::ClassLibrary.Messages.Protobuf.Coordinates_M direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClassLibrary.Messages.Protobuf.Coordinates_M Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "LastUpdate" field.</summary>
    public const int LastUpdateFieldNumber = 5;
    private double lastUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LastUpdate {
      get { return lastUpdate_; }
      set {
        lastUpdate_ = value;
      }
    }

    /// <summary>Field number for the "EventId" field.</summary>
    public const int EventIdFieldNumber = 6;
    private string eventId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TTL" field.</summary>
    public const int TTLFieldNumber = 7;
    private double tTL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TTL {
      get { return tTL_; }
      set {
        tTL_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as World_M);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(World_M other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (Change != other.Change) return false;
      if (!object.Equals(Location, other.Location)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastUpdate, other.LastUpdate)) return false;
      if (EventId != other.EventId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TTL, other.TTL)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
      if (Change != global::ClassLibrary.Messages.Protobuf.Change.DamageAgent) hash ^= Change.GetHashCode();
      if (location_ != null) hash ^= Location.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (LastUpdate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastUpdate);
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (TTL != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TTL);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.Change.DamageAgent) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Change);
      }
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (direction_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Direction);
      }
      if (LastUpdate != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(LastUpdate);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (TTL != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(TTL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.Change.DamageAgent) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Change);
      }
      if (location_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Location);
      }
      if (direction_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Direction);
      }
      if (LastUpdate != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(LastUpdate);
      }
      if (EventId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EventId);
      }
      if (TTL != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(TTL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
      }
      if (Change != global::ClassLibrary.Messages.Protobuf.Change.DamageAgent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Change);
      }
      if (location_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (LastUpdate != 0D) {
        size += 1 + 8;
      }
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (TTL != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(World_M other) {
      if (other == null) {
        return;
      }
      if (other.EntityId.Length != 0) {
        EntityId = other.EntityId;
      }
      if (other.Change != global::ClassLibrary.Messages.Protobuf.Change.DamageAgent) {
        Change = other.Change;
      }
      if (other.location_ != null) {
        if (location_ == null) {
          Location = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
        }
        Location.MergeFrom(other.Location);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.LastUpdate != 0D) {
        LastUpdate = other.LastUpdate;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.TTL != 0D) {
        TTL = other.TTL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Change = (global::ClassLibrary.Messages.Protobuf.Change) input.ReadEnum();
            break;
          }
          case 26: {
            if (location_ == null) {
              Location = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Location);
            break;
          }
          case 34: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 41: {
            LastUpdate = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 57: {
            TTL = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityId = input.ReadString();
            break;
          }
          case 16: {
            Change = (global::ClassLibrary.Messages.Protobuf.Change) input.ReadEnum();
            break;
          }
          case 26: {
            if (location_ == null) {
              Location = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Location);
            break;
          }
          case 34: {
            if (direction_ == null) {
              Direction = new global::ClassLibrary.Messages.Protobuf.Coordinates_M();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 41: {
            LastUpdate = input.ReadDouble();
            break;
          }
          case 50: {
            EventId = input.ReadString();
            break;
          }
          case 57: {
            TTL = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
