# Zookeeper parameters
#zookeeper:
#  replicaCount: 3
#  persistence:
#    size: 1Gi

# Kafka External parameters
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  controller:
    service:
      type: LoadBalancer
  broker:
    service:
      type: LoadBalancer
serviceAccount:
  create: true
rbac:
  create: true

# Kafka Security parameters
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
    enabled: true
    type: LoadBalancer

# Kafka Controller parameters
controller:
  replicaCount: 1 #3
  persistence:
    size: 1Gi
  automountServiceAccountToken: true

# Kafka Broker parameters
broker:
  automountServiceAccountToken: true
  resources:
    requests:
      cpu: "100m"     # Request 100 millicpu (1/10 CPU core)
      memory: "100Mi" # Request 100 MB of memory
    limits:
      cpu: "200m"     # Limit to 200 millicpu (1/10 CPU core)
      memory: "200Mi" # Limit to 200 MB of memory
#broker:
#  replicaCount: 3
#  persistence:
#    size: 1Gi
#
#replicaCount: 3
