version: "3.9"

services:

  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    networks:
      sharednetwork:

networks:
  sharednetwork:
    name: "sharednetwork"
