replicaCount: 3
service:
  type: NodePort
  nodePorts:
    kafka: 31090
externalAccess:
  controller:
    service:
      type: NodePort
      port: 9094
      nodePorts:
        - 31090
        - 31091
        - 31092
  enabled: true
  service:
    type: NodePort
    port: 9094
    nodePorts:
      - 31090
      - 31091
      - 31092
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT