apiVersion: v1
kind: Service
metadata:
  name: projectile-service
spec:
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8080
  selector:
    app: projectile-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectile-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: projectile-service
    spec:
      containers:
        - name: projectile-service
          image: ghcr.io/antje12/10-master/projectile-service:{IMG_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ProjectileService/Status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-X", "GET", "http://localhost:8080/projectileservice/stop"]
