apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-2
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181 
    - name: server
      port: 2888
      targetPort: 2888 
    - name: leader
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper-service-2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-service-2
  template:
    metadata:
      labels:
        app: zookeeper-service-2
    spec:
      containers:
        - name: zookeeper-service-2
          image: confluentinc/cp-zookeeper:7.2.1
          ports:
            - containerPort: 2181 # Client port
            - containerPort: 2888 # Server communication port
            - containerPort: 3888 # Leader election port
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "2"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-service-1:2888:3888;0.0.0.0:2888:3888;zookeeper-service-3:2888:3888"
            - name: ZOOKEEPER_ELECTION_PORT_BIND_RETRY
              value: "10"  # Increase the number of retries
