apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
spec:
  ports:
    - name: external
      port: 19092
      targetPort: 19092
      nodePort: 30002
    - name: internal
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-service-2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service-2
  template:
    metadata:
      labels:
        app: kafka-service-2
    spec:
      containers:
        - name: kafka-service-2
          image: confluentinc/cp-kafka:7.2.1
          ports:
            - containerPort: 19092
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service-1:2181,zookeeper-service-2:2181,zookeeper-service-3:2181"
            - name: KAFKA_PARTITION_ASSIGNMENT_STRATEGY
              value: "org.apache.kafka.clients.consumer.RoundRobinAssignor"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service-2:9092,EXTERNAL://34.32.38.33:30002"
