apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  ports:
    - name: redis-server
      port: 6379
      targetPort: 6379
      nodePort: 30006
    - name: redis-insight
      port: 8001
      targetPort: 8001
      nodePort: 30005
  selector:
    app: redis-stack
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis-stack
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6379
            - containerPort: 8001
          volumeMounts:
            - mountPath: /data
              name: redis-persistent-storage
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: redis-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
