architecture: "sharded"

# MongoDB Config server parameters
configsvr:
  replicaCount: 3
  persistence:
    size: 1Gi

# MongoDB Mongos parameters
mongos:
  replicaCount: 2
  service:
    type: NodePort
    nodePort: 30007

# MongoDB Shards parameters
shards: 1 #3
shardsvr:
  dataNode:
    replicaCount: 3
  persistence:
    size: 1Gi

# MongoDB Authentication parameters
auth:
  enabled: true
  rootUser: "root"
  rootPassword: "password" # You should change this password
  replicaSetKey: "replicaSetKey" # You should change this key
