apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: schema-registry-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-service
  template:
    metadata:
      labels:
        app: schema-registry-service
    spec:
      containers:
        - name: schema-registry-service
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry-service"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN
              value: "*"
            - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS
              value: "GET,POST,PUT,OPTIONS"
