apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
spec:
  ports:
    - name: external
      port: 19092
      targetPort: 19092
      nodePort: 30001
    - name: internal
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-service-1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service-1
  template:
    metadata:
      labels:
        app: kafka-service-1
    spec:
      containers:
        - name: kafka-service-1
          image: confluentinc/cp-kafka:7.2.1
          ports:
            - containerPort: 19092
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service-1:2181,zookeeper-service-2:2181,zookeeper-service-3:2181"
            - name: KAFKA_PARTITION_ASSIGNMENT_STRATEGY
              value: "org.apache.kafka.clients.consumer.RoundRobinAssignor"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service-1:9092,EXTERNAL://34.32.47.73:30001"
          resources:
            requests:
              #cpu: "100m"     # Request xxx millicpu (CPU core)
              memory: "200Mi" # Request xxx MB of memory
            limits:
              #cpu: "200m"     # Request xxx millicpu (CPU core)
              memory: "400Mi" # Limit to xxx MB of memory
