apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-service
  template:
    metadata:
      labels:
        app: zookeeper-service
    spec:
      containers:
        - name: zookeeper-service
          image: confluentinc/cp-zookeeper:7.2.1
          ports:
            - containerPort: 2181
          resources:
            requests:
              cpu: "200m"     # Request 50 millicpu (1/20 CPU core)
              memory: "200Mi" # Request 50 MB of memory
            limits:
              cpu: "200m"     # Request 50 millicpu (1/20 CPU core)
              memory: "200Mi" # Limit to 50 MB of memory
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-service:2888:3888"
