version: "3.9"

services:

  kowl:
    container_name: kowl
    image: quay.io/cloudhut/kowl:master 
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: 34.32.59.114:9094,34.32.47.73:9094,34.32.30.150:9094
    networks:
      sharednetwork:

networks:
  sharednetwork:
    name: "sharednetwork"
