apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  ports:
    - name: http
      port: 8084
      protocol: TCP
      targetPort: 8080
  selector:
    app: world-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: world-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
        - name: world-service
          image: ghcr.io/antje12/10-master/world-service:{IMG_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /WorldService/Status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-X", "GET", "http://localhost:8080/worldservice/stop"]
