apiVersion: v1
kind: Service
metadata:
  name: collision-service
spec:
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: collision-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collision-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collision-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: collision-service
    spec:
      containers:
        - name: collision-service
          image: ghcr.io/antje12/10-master/collision-service:{IMG_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /CollisionService/Status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
