apiVersion: v1
kind: Service
metadata:
  name: input-service
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: input-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: input-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: input-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: input-service
    spec:
      containers:
        - name: input-service
          image: ghcr.io/antje12/10-master/input-service:{IMG_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /InputService/Status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-X", "GET", "http://localhost:8080/inputservice/stop"]
