name: Build action
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-and-deploy-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Login to container registry 
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push InputService image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./TidesOfPower
          file: ./TidesOfPower/InputService/Dockerfile
          push: true
          tags: |
            ghcr.io/antje12/10-master/input-service:GA-${{ github.sha }},
            ghcr.io/antje12/10-master/input-service:latest

      - name: Build and push CollisionService image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./TidesOfPower
          file: ./TidesOfPower/CollisionService/Dockerfile
          push: true
          tags: |
            ghcr.io/antje12/10-master/collision-service:GA-${{ github.sha }},
            ghcr.io/antje12/10-master/collision-service:latest

      - name: Build and push WorldService image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./TidesOfPower
          file: ./TidesOfPower/WorldService/Dockerfile
          push: true
          tags: |
            ghcr.io/antje12/10-master/world-service:GA-${{ github.sha }},
            ghcr.io/antje12/10-master/world-service:latest

      - name: Build and push ProjectileService image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./TidesOfPower
          file: ./TidesOfPower/ProjectileService/Dockerfile
          push: true
          tags: |
            ghcr.io/antje12/10-master/projectile-service:GA-${{ github.sha }},
            ghcr.io/antje12/10-master/projectile-service:latest
