name: Build action
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-and-deploy-input-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Login to container registry 
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./TidesOfPower
          file: ./TidesOfPower/InputService/Dockerfile
          push: true
          tags: ghcr.io/antje12/10-master/input-service:GA-${{ github.sha }}
  
  #build-and-deploy-collision-service-image:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code base
  #      uses: actions/checkout@v2
  #
  #    - name: Login to container registry 
  #      uses: docker/login-action@v3
  #      with: 
  #        registry: ghcr.io 
  #        username: ${{ github.actor }} 
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    
  #    - name: Build and push image to registry
  #      run: docker buildx build --push --file TidesOfPower/CollisionService/Dockerfile --tag ghcr.io/antje12/10-master/collisionservice:GA-${{ github.sha }} .
  #
  #build-and-deploy-world-service-image:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code base
  #      uses: actions/checkout@v2
  #
  #    - name: Login to container registry 
  #      uses: docker/login-action@v3
  #      with: 
  #        registry: ghcr.io 
  #        username: ${{ github.actor }} 
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    
  #    - name: Build and push image to registry
  #      run: docker buildx build --push --file TidesOfPower/WorldService/Dockerfile --tag ghcr.io/antje12/10-master/worldservice:GA-${{ github.sha }} .
  #
  #build-and-deploy-tick-service-image:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code base
  #      uses: actions/checkout@v2
  #
  #    - name: Login to container registry 
  #      uses: docker/login-action@v3
  #      with: 
  #        registry: ghcr.io 
  #        username: ${{ github.actor }} 
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    
  #    - name: Build and push image to registry
  #      run: docker buildx build --push --file TidesOfPower/TickService/Dockerfile --tag ghcr.io/antje12/10-master/tickservice:GA-${{ github.sha }} .
